fragment BlogParts on Blog {
  __typename
  title
  pubDate
  location
  main_image
  gallery_url
  video_url
  tags {
    __typename
    video
    photo
    drone
    evenementiel
    studio
    immobilier
    industriel
    tourisme
    voyage
    paysage
    sports
    associatif
    divers
    culture
    gastronomie
    musique
  }
  body
}
